modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${github}/issues"

[[mods]]
    modId="visceralib_model_loading_api_v1"
    version="${version}"
    displayName="VisceraLib Model Loading API (v1)"
    authors="${authors}"
    credits="${contributors}"
    description="Contains code to help with loading different model formats."
    logoFile="assets/visceralib_model_loading_api_v1/logo.png"
    logoBlur=false
    displayURL="${github}"

[[mixins]]
    config="mixins/visceralib-model-loading-api-v1-common.client.mixins.json"
[[mixins]]
    config="mixins/visceralib-model-loading-api-v1-neoforge.client.mixins.json"
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[dependencies.visceralib_model_loading_api_v1]]
    modId="neoforge"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="CLIENT"
[[dependencies.visceralib_model_loading_api_v1]]
    modId="minecraft"
    type="required"
    versionRange="[${minMinecraft},)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.visceralib_model_loading_api_v1]]
    modId="visceralib_core"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="CLIENT"

[modproperties.modmenu]
    badges=[ "library" ]
[modproperties.modmenu_parent]
    id="visceralib"
    name="VisceraLib"
    description="${description}"
    icon="assets/visceralib_model_loading_api_v1/logo.png"
    badges= [ "library" ]