modLoader="javafml"
loaderVersion="*"
license="${license}"

[[mods]]
modId="${id}"
displayName="${name}"
description="${description}"
authors="${authors}"
version="${version}"
logoFile="icon.png"
logoBlur=false

[[dependencies."${id}"]]
modId="architectury"
type="required"
versionRange="${archApi}"
ordering="AFTER"
side="BOTH"

[[dependencies."${id}"]]
modId="flywheel"
type="required"
versionRange="${flywheel}"
ordering="AFTER"
side="CLIENT"

[[dependencies."${id}"]]
modId="veil"
type="required"
versionRange="${veil}"
ordering="AFTER"
side="CLIENT"

[[dependencies."${id}"]]
modId="ponder"
type="required"
versionRange="${ponder}"
ordering="AFTER"
side="BOTH"